##**Decision Tree**
It is a tree based model that makes decision based on inputs (questions asked)
* DecisionTreeRegression = For regression problem
* DecisionTreeClassifier = For classification problem

###**Components of Decision Tree**
1. Root Node: The very first question that you ask, top of the tree. (impurest)
2. Decision nodes: A point where the another question is asked
    * These are in between the root node and end result
3. Leaf node(Terminal Node): Final answer or decision we get
4. Branches(edges): These are the arrows from one node to another

###**Ways to make decision**
1. **Gini Impurity**
    * It measures how mixed a group is
    * A pure group = all same class = gini value will be 0
    * lower gini = Better split

2. **Entropy**
    * Entropy = The level of disorder in our data
    * The goal is to reduce the randomness from the data
    * Lower entropy = less randomness

3. **Information Gain**
    * Info Gain = How much order we gain after a split
    * The more info gain means split towards more pure data

##**Random Forest**
It is like a group of decision tress that work together to make better predictions, instead of building one DT, it builds many trees and takes vote or avg to make the final decision.
* It follows the concept of ensemble learning (combining the prediction of multiple models to get better results)
* It follows bootstrap aggregation (Bagging) where we select random data from the dataset and then train each decision trees one by one.

###**For evaluation**
Once all the trees are build:
* For classification: Each tree votes for a class, the majority wins.
* For regression: The output is the avg of all the tree predictions.

###**Underfiiting and Overfitting
* **UnderFitting**: When the models performance poor on both training and Testing data
    * To reduce the underfitting: l1/l2 Regularization (or increase the amount training data)

* **Overfitting**: When model performs good on training data but failed to perform a good on new data.
    * To overcome overfitting: reduce the tree depth, L1 and L2, use Cross Validations, increase the testing data, use ensemble techniques

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv('/content/customer_churn.csv')

In [ ]:
df.head()

,Names,Age,Total_Purchase,Account_Manager,Years,Num_Sites,Onboard_date,Location,Company,Churn
0,Cameron Williams,42.0,11066.80,0,7.22,8.0,2013-08-30 07:00:40,"10265 Elizabeth Mission Barkerburgh, AK 89518",Harvey LLC,1
1,Kevin Mueller,41.0,11916.22,0,6.50,11.0,2013-08-13 00:38:46,"6157 Frank Gardens Suite 019 Carloshaven, RI 1...",Wilson PLC,1
2,Eric Lozano,38.0,12884.75,0,6.67,12.0,2016-06-29 06:20:07,"1331 Keith Court Alyssahaven, DE 90114","Miller, Johnson and Wallace",1
3,Phillip White,42.0,8010.76,0,6.71,10.0,2014-04-22 12:43:12,"13120 Daniel Mount Angelabury, WY 30645-4695",Smith Inc,1
4,Cynthia Norton,37.0,9191.58,0,5.56,9.0,2016-01-19 15:31:15,"765 Tricia Row Karenshire, MH 71730",Love-Jones,1

In [ ]:
df.shape

(900, 10)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 900 entries, 0 to 899
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Names            900 non-null    object
 1   Age              900 non-null    float64
 2   Total_Purchase   900 non-null    float64
 3   Account_Manager  900 non-null    int64
 4   Years            900 non-null    float64
 5   Num_Sites        900 non-null    float64
 6   Onboard_date     900 non-null    object
 7   Location         900 non-null    object
 8   Company          900 non-null    object
 9   Churn            900 non-null    int64
dtypes: float64(4), int64(2), object(4)
memory usage: 70.4+ KB

In [ ]:
df.isnull().sum()

Names              0
Age                0
Total_Purchase     0
Account_Manager    0
Years              0
Num_Sites          0
Onboard_date       0
Location           0
Company            0
Churn              0
dtype: int64

In [ ]:
#df['TTotalCharges'].astype(float)

In total charges column there are some white spaces' ' ' '